sudo: required
services:
  - docker

before_install:
  - docker image build -f Dockerfile -t juliocesarmidia/php-unit-test .

script:
  - docker container run --name php-unit-test juliocesarmidia/php-unit-test
